name: Produce and Publish
on:
  push:
    tags:
    - 'v*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get Githash
        id: git_hash
        run: echo "::set-output name=git_hash::$(git rev-parse --short "$GITHUB_SHA")"
      - name: Get Git Branch
        id: git_branch
        run: echo "::set-output name=git_branch::${GITHUB_REF#refs/heads/}"
      - name: Set Version in Document
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "@@version@@"
          replace: "${{ steps.date.outputs.date }}-${{ steps.git_branch.outputs.git_branch }}-${{ steps.git_hash.outputs.git_hash }}"
          regex: false
      - name: Create github_artifacts
        run: mkdir -p github_artifacts
      - name: Compile LaTeX Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: move pdf
        run: mv main.pdf github_artifacts
      - name: Install ghostscript
        run: sudo apt install ghostscript -y
      - name: Workaround ghostscript vunerability protection
        # A vunerabillty that existed in ghostscript no longer exists.  This is to work around the temporary protection
        # that was put in place
        # https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion
        run: sudo sed -i 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
      - name: Generate Thumbnail for Page 1
        #uses: jruipinto/ImageMagick-action@v1
        run: convert -density 700 -resize 10% -append -quality 98 -alpha remove rb-cv.pdf[0] ac-cv-thumbnail-p1.jpg
      - name: move Thumbnail for Page 1
        run: mv ac-cv-thumbnail-p1.jpg github_artifacts
      - name: Generate Thumbnail for Page 2
        uses: jruipinto/ImageMagick-action@v1
        with:
          command: convert -density 700 -resize 10% -append -quality 98 -alpha remove rb-cv.pdf[1] ac-cv-thumbnail-p2.jpg
      - name: move Thumbnail for Page 2
        run: mv ac-cv-thumbnail-p2.jpg github_artifacts
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_artifacts
          path: ./github_artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true

  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME